apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: workload
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workload
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
  - type: External
    external:
      metric:
        name: custom.googleapis.com|balancer
        selector:
          matchLabels:
            resource.labels.project_id: REPLACE
            resource.labels.location: REPLACE
            resource.labels.namespace: REPLACE
            resource.labels.node_id: default-workload
      target:
        type: Value
        value: 100

